{"trial_id": "00", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "conv_1_filter", "default": 32, "conditions": [], "values": [32, 64], "ordered": true}}, {"class_name": "Choice", "config": {"name": "conv_1_kernel", "default": 3, "conditions": [], "values": [3], "ordered": true}}, {"class_name": "Choice", "config": {"name": "conv_2_filter", "default": 32, "conditions": [], "values": [32, 64], "ordered": true}}, {"class_name": "Choice", "config": {"name": "conv_2_kernel", "default": 3, "conditions": [], "values": [3], "ordered": true}}, {"class_name": "Choice", "config": {"name": "dense_units", "default": 128, "conditions": [], "values": [128, 256], "ordered": true}}, {"class_name": "Choice", "config": {"name": "dropout", "default": 0.1, "conditions": [], "values": [0.1, 0.3, 0.5], "ordered": true}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.001, "conditions": [], "values": [0.001, 0.0001], "ordered": true}}], "values": {"conv_1_filter": 32, "conv_1_kernel": 3, "conv_2_filter": 64, "conv_2_kernel": 3, "dense_units": 128, "dropout": 0.1, "learning_rate": 0.001}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/sakshamkapoor/miniconda3/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/sakshamkapoor/miniconda3/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/sakshamkapoor/miniconda3/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/Users/sakshamkapoor/miniconda3/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/Users/sakshamkapoor/miniconda3/lib/python3.9/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"/Users/sakshamkapoor/miniconda3/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/sakshamkapoor/miniconda3/lib/python3.9/site-packages/keras/src/layers/input_spec.py\", line 227, in assert_input_compatibility\n    raise ValueError(\nValueError: Exception encountered when calling Sequential.call().\n\n\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 6400, but received input with shape (None, 30976)\u001b[0m\n\nArguments received by Sequential.call():\n  \u2022 inputs=tf.Tensor(shape=(None, 96, 96, 3), dtype=float32)\n  \u2022 training=True\n  \u2022 mask=None\n"}